# backend/openapi.yaml (create this file if Choreo requires a schema)
openapi: 3.0.0
info:
  title: Scott Overhead Doors API
  version: 1.0.0
  description: Backend API for Scott Overhead Doors management system
servers:
  - url: /
    description: Main API server
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
                  version:
                    type: string
  /api/health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                  version:
                    type: string
  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                  message:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        status_code:
          type: integer