
version: 0.1
components:
  - name: scott-backend
    type: service
    source:
      path: ./backend
    spec:
      container:
        image: 
          name: scott-backend
          tag: latest
        ports:
          - containerPort: 5000
        securityContext:
          runAsUser: 10014
          runAsGroup: 10014
          runAsNonRoot: true
        env:
          - name: FLASK_ENV
            value: production
          - name: DATABASE_URL
            value: postgresql://ScottAdmin:Rollup22@scottohd.postgres.database.azure.com:5432/scottohd?sslmode=require
          # Alternative individual database configuration variables (optional)
          - name: DB_HOST
            value: scottohd.postgres.database.azure.com
          - name: DB_USER
            value: ScottAdmin
          - name: DB_PASSWORD
            value: "Rollup22"
          - name: DB_NAME
            value: scottohd
          - name: DB_PORT
            value: "5432"
  - name: scott-frontend
    type: webapp
    source:
      path: ./frontend
    spec:
      container:
        image:
          name: scott-frontend
          tag: latest
        ports:
          - containerPort: 8080
        securityContext:
          runAsUser: 10014
          runAsGroup: 10014
          runAsNonRoot: true