"""Add truck_assignment to Job model

Revision ID: 552f72e64de3
Revises: 
Create Date: 2025-07-03 02:52:19.238498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552f72e64de3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_dispatch')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_assignment', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('truck_assignment')

    op.create_table('daily_dispatch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('truck_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_date', sa.DATE(), nullable=False),
    sa.Column('job_order', sa.INTEGER(), nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'assignment_date', name='_job_date_uc')
    )
    # ### end Alembic commands ###
