"""Add location column to Door table

Revision ID: c448c7f2a538
Revises: 
Create Date: 2025-04-08 21:43:36.318646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c448c7f2a538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
